<div class="page-title">
	<h2>Main menu</h2>
</div>
<div id="columns" class="index">
	<div class="column">
		<div class="sub-title">
			<h3>Shortcuts</h3>
		</div>
		<div id="shortcuts">
			<a class="shortcut add-project" href="<?php echo ROOT; ?>admin/project/new">Add Project</a>
			<a class="shortcut add-customer" href="<?php echo ROOT; ?>admin/customer/new">Add Customer</a>
			<a class="shortcut add-resource" href="<?php echo ROOT; ?>admin/resource/new">Add Resource</a>
			<a class="shortcut goto-archive" href="<?php echo ROOT; ?>admin/archive">Project Archive</a>
			<a class="shortcut goto-reports" href="<?php echo ROOT; ?>admin/export">Excel Report</a>
			<?php /* Link added for pleasure, do only remove comment area at desperate times
			<a class="shortcut goto-awesome" href="http://www.pornhub.com/">Go to Awesome</a> */ ?>
			<div class="clear"></div>
		</div>
		<div class="sub-title">
			<h3>Calender</h3>
		</div>
		<?php echo $this->form; ?>
			<script type="text/javascript">
			$(document).ready(function(){
				$('#resource_id').prop('selectedIndex',-1);
			});

			
			function getId()
			{
				var unavailableDates;
				var e = document.getElementById("resource_id");
				var a = e.options[e.selectedIndex].value;
				$.post('<?php echo ROOT; ?>ajax/unavailable.php',{postId:a},
				function(data)
				{
					unavailableDates = new Array();
					for(var i = 0; i < data.length; i++) 
					{
						 unavailableDates[i] = data[i].date;
					}
					$("#calendar").datepicker("destroy");
					$("#calendar").datepicker(
					{
						dateFormat: 'yy-mm-dd',
						beforeShowDay: function(date)
						{			
							dmy = date.getFullYear() + "-" + (date.getMonth() + 1) + "-" + date.getDate();
							if($.inArray(dmy, unavailableDates) == -1)
							{
								return [true, ""];
							}
							else
							{
								return [false, "Unavailable"];
							}
						}
					});
					
					
				}, "json").fail(function()
									{
										$("#calendar").datepicker("destroy");
										$("#calendar").datepicker(
										{
											dateFormat: 'yy-mm-dd'
										});
									});
			}
			$(function(){
				$("#calendar").datepicker({
					dateFormat: 'yy-mm-dd'
				});
			});
			</script>
			<div id="calendar"></div>
	</div>
	<div class="column">
		<div class="sub-title">
			<h3>Active Projects</h3>
		</div>
		<?php foreach($this->projects->getProjects() as $project): ?>
		<?php
		$parts = $this->projects->getParts($project->project_id);
		$tot = count($parts);
		$count = 0;
		$percentage = 0;
		foreach($parts as $part){ 
			if($part->status == '3'){ $count++; } 
			$percentage += 100 / $tot / 3 * $part->status;
		}
		?>
		<div class="project">
			<div class="info">
				<a href="<?php echo ROOT; ?>admin/project/mode/edit/id/<?php echo $project->project_id; ?>"><h3><?php echo $project->title; ?></h3></a>
				<span><?php echo $project->programmecode; ?></span>
				<span>
					<?php
					
					$mainCustomer = $this->customer->getMainCustomer($project->project_id);
					if($mainCustomer){ echo $mainCustomer->fullname; }
					?>
				</span>
			</div>
			<div class="stats">
				<div class="parts"><b><?php echo $count; ?></b> out of <b><?php echo $tot; ?></b> parts done</div>
				<div class="deadline">Deadline: <b><?php echo $project->deadline;?></b></div>
			</div>
			<div class="progress not-started">
				<div class="in-progress" style="opacity:<?php if($percentage > 33){ echo '1.0'; }else{ echo number_format($percentage / 33, '.', ''); } ?>">
					<div class="finalizing" style="opacity:<?php if($percentage > 66){ echo '1.0'; }elseif($percentage > 33){ echo number_format(($percentage - 33) / 33, '.', ''); }else{ echo '0'; } ?>">
						<div class="complete" style="opacity:<?php if($percentage > 99){ echo '1.0'; }elseif($percentage > 66){ echo number_format(($percentage - 66) / 33, '.', ''); }else{ echo '0'; } ?>">
							&nbsp;
						</div>
					</div>
				</div>
				<div class="percentage">
					<?php echo round($percentage); ?>%
				</div>
			</div>
		</div>
		<?php endforeach; ?>
	</div>
</div>