<div class="page-title">
	<h2><?php echo $this->page_title; ?></h2>
</div>
<?php if(isset($this->mode)): ?>
<div id="columns">
	<div class="column">
		<div class="sub-title">
			<h3>General Information</h3>
			<?php if($this->mode != 'new'): ?>
				<script type="text/javascript">
					function mailPopUp(url) 
					{
						popupWindow = window.open(url,'popUpWindow','height=500,width=500,left=100,top=100,resizable=yes,scrollbars=yes,toolbar=no,menubar=no,location=no,directories=no, status=yes');
					}
				</script>
				<a class="button" href="<?php echo ROOT; ?>admin/mail/id/<?php echo $this->project->project_id; ?>" onclick="mailPopUp(this.href);return false">Send status mail</a>
				<a class="button" href="<?php echo ROOT; ?>admin/project/archive/<?php echo $this->project->project_id; ?>" onclick="return confirm('Archive this project?');">Archive</a>
				<a class="button" href="<?php echo ROOT; ?><?php echo $this->project->urlkey; ?>">View</a>
			<?php endif; ?>
			<script type="text/javascript">
			$(function(){
				$("#deadline").datepicker({
					dateFormat: 'yy-mm-dd'
				});
			});
			</script>
		</div>
		<?php echo $this->form; ?>
	</div>
	<div class="column">
		<div class="parts">
			<div class="sub-title">
				<h3>Project Parts</h3>
				<?php if($this->mode != 'new'): ?>
					<a class="button new" href="<?php echo ROOT; ?>admin/part/new/<?php echo $this->project->project_id; ?>"><b>+</b> Add Part</a>
				<?php endif; ?>
			</div>
			<?php if(isset($this->parts) && count($this->parts)): ?>
				<script type="text/javascript">
				
				function goto(loc, part_name){
					if(confirm('Are you sure you want to delete "' + part_name + '"')){
						window.location.href = loc;
					}
				}
					
				</script>
				<?php foreach($this->parts as $part): ?>
					<div class="part">
						<div class="info">
							<h4><?php echo $part->title; ?></h4>
						</div>
						<div class="status">
							<a <?php if($part->status == 0){ echo 'class="active"'; } ?> href="#">Not Started</a>
							<a <?php if($part->status == 1){ echo 'class="active"'; } ?> href="#">In Progress</a>
							<a <?php if($part->status == 2){ echo 'class="active"'; } ?> href="#">Finalizing</a>
							<a <?php if($part->status == 3){ echo 'class="active"'; } ?> href="#">Completed</a>
						</div>
						<div class="comment">
							<?php echo substr($part->comment, 0, 230); ?><?php if(strlen($part->comment) > 230){ echo '...'; } ?>
							<div class="actions">
								<a class="delete" href="javascript:goto('<?php echo ROOT; ?>admin/part/delete/<?php echo $this->project->project_id; ?>/<?php echo $part->part_id; ?>', '<?php echo $part->title; ?>')">Delete</a>
								<a class="edit" href="<?php echo ROOT; ?>admin/part/edit/<?php echo $this->project->project_id; ?>/<?php echo $part->part_id; ?>">Edit</a>
								<a class="assign" href="<?php echo ROOT; ?>admin/resourcedate/new/<?php echo $this->project->project_id; ?>/<?php echo $part->part_id; ?>/">Assign resource</a>
							</div>
						</div>
					</div>
				<?php endforeach; ?>
			<?php elseif($this->mode == 'new'): ?>
				<div class="notice">
					You must save the project before you can add parts!
				</div>
			<?php else: ?>
				<div class="notice">
					No parts added to the project yet!
				</div>
			<?php endif; ?>
		</div>
		<div class="sub-title">
			<h3>Project Customers</h2>
			<?php if($this->mode != 'new'): ?>
				<a class="button new" href="<?php echo ROOT; ?>admin/projectcustomer/new/<?php echo $this->project->project_id; ?>"><b>+</b> Add Customer</a>
			<?php endif; ?>
		</div>
		<?php if(isset($this->maincustomer) && count($this->maincustomer)): ?>
			<?php if(isset($this->maincustomer)): ?>






				<div class="contact">
					<div class="left">
						<h4><?php echo $this->maincustomer[0]['fullname']; ?></h4>
						<?php echo $this->maincustomer[0]['unit']; ?>
					</div>
					<div class="right">
						<?php echo $this->maincustomer[0]['mail']; ?>
						<br /><?php echo $this->maincustomer[0]['phone']; ?>
					</div>
				</div>
			<?php endif; ?>
			<?php foreach($this->customers as $customer): ?>





			<div class="contact">
				<div class="left">
					<h4><?php echo $customer['fullname']; ?></h4>
				</div>
				<div class="right">
					<?php echo $customer['mail']; ?>
				</div>
			</div>
			<?php endforeach; ?>
		<?php elseif($this->mode == 'new'):?>
		<div class="notice">
			You must save the project before you can add customers!
		</div>
		<?php else: ?>
		<div class="notice">
			No customers added to the project yet!
		</div>
		<?php endif; ?>
	</div>
</div>
<?php else: ?>
<div class="sub-title">
	<h3>Active Projects</h3>
	<a class="button new" href="<?php echo ROOT; ?>admin/project/new"><b>+</b> Add Project</a>
</div>
<?php foreach($this->projects->getProjects() as $project): ?>
<?php
$parts = $this->projects->getParts($project->project_id);
$tot = count($parts);
$count = 0;
$percentage = 0;
foreach($parts as $part){ 
	if($part->status == '3'){ $count++; } 
	$percentage += 100 / $tot / 3 * $part->status;
}
?>
<div class="project">
	<div class="info">
		<a href="<?php echo ROOT; ?>admin/project/edit/<?php echo $project->project_id; ?>"><h3><?php echo $project->title; ?></h3></a>
		<span><?php echo $project->programmecode; ?></span>
		<span>
			<?php
			
			$mainCustomer = $this->customer->getMainCustomer($project->project_id);
			if($mainCustomer){ echo $mainCustomer->fullname; }
			?>
		</span>
	</div>
	<div class="stats">
		<div class="parts"><b><?php echo $count; ?></b> out of <b><?php echo $tot; ?></b> parts done</div>
		<div class="deadline">Deadline: <b><?php echo $project->deadline;?></b></div>
	</div>
	<div class="progress not-started">
		<div class="in-progress" style="opacity:<?php if($percentage > 33){ echo '1.0'; }else{ echo number_format($percentage / 33, 1, '.', ''); } ?>">
			<div class="finalizing" style="opacity:<?php if($percentage > 66){ echo '1.0'; }elseif($percentage > 33){ echo number_format(($percentage - 33) / 33, 1, '.', ''); }else{ echo '0'; } ?>">
				<div class="complete" style="opacity:<?php if($percentage > 99){ echo '1.0'; }elseif($percentage > 66){ echo number_format(($percentage - 66) / 33, 1, '.', ''); }else{ echo '0'; } ?>">
					&nbsp;
				</div>
			</div>
		</div>
		<div class="percentage">
			<?php echo round($percentage); ?>%
		</div>
	</div>
</div>
<?php endforeach; ?>
<?php endif; ?>