<div class="page-title">

	<h2><?php echo $this->page_title; ?></h2>

</div>

<div id="columns">

	<div class="column">

		<div class="sub-title">

			<h3>Resource Information</h3><a class="button new" href="<?php echo ROOT; ?>admin/project/edit/<?php echo $this->id; ?>">Go back to Project</a>

		</div>

	<script type="text/javascript">
	$(document).ready(function(){
		$('#resource_id').prop('selectedIndex',-1);
	});

	
	function getId()
	{
		var unavailableDates;
		var e = document.getElementById("resource_id");
		var a = e.options[e.selectedIndex].value;
		$.post('<?php echo ROOT; ?>ajax/unavailable.php',{postId:a},
		function(data)
		{
			unavailableDates = new Array();
			for(var i = 0; i < data.length; i++) 
			{
				 unavailableDates[i] = data[i].date;
			}
			$("#date").datepicker("destroy");
			$("#date").datepicker(
			{
				dateFormat: 'yy-mm-dd',
				beforeShowDay: function(date)
				{			
					dmy = date.getFullYear() + "-" + (date.getMonth() + 1) + "-" + date.getDate();
					if($.inArray(dmy, unavailableDates) == -1)
					{
						return [true, ""];
					}
					else
					{
						return [false, "Unavailable"];
					}
				}
			});
			
			
		}, "json").fail(function()
							{
								$("#date").datepicker("destroy");
								$("#date").datepicker(
								{
									dateFormat: 'yy-mm-dd'
								});
							});
	}
	
	/*$(function(){
		$("#date").datepicker({
			dateFormat: 'yy-mm-dd'
		});
	});*/
	</script>
	<?php echo $this->form;	?>
	
	</div>

	<div class="column">

		

	</div>

</div>