<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
	<meta name="viewport" content="width=device-width" />
	<?php echo $this->headTitle(); ?>
	<?php echo $this->loadSkin($this->skin); ?>
	<?php echo $this->headScript(); ?>
	<?php echo $this->headLink(); ?>
    <?php echo $this->dojo(); ?>
    <?php echo $this->dojo()->addStylesheetModule('dijit.themes.tundra'); ?>
</head>
<body id="admin" class="tundra">
 
<div id="wrapper">
	<div id="header">
		<div id="hleft">
			<a class="link" id="link-home" href="<?php ROOT; ?>/admin">Home</a>
			<a class="link" id="link-project" href="<?php ROOT; ?>/admin/project/mode/new">Add Project</a>
			<a class="link" id="link-resource" href="<?php ROOT; ?>/admin/resource/mode/new">Add Resource</a>
		</div>
		<div id="hright">
			<a class="link" id="link-logout" href="">Log out</a>
		</div>
	</div>
	<div id="content">
		<?php  echo $this->layout()->content ?>
	</div>
</div>


</body>
</html>