<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=UTF-8" />
	<meta name="viewport" content="width=device-width" />
	<?php echo $this->headTitle(); ?>
	<?php echo $this->loadSkin($this->skin); ?>
	<?php echo $this->headLink(); ?>
	<?php echo $this->jQuery();?>
</head>
<body id="admin" class="tundra">
 
<div id="wrapper">
	<div id="header">
		<div id="hleft">
			<a class="link" id="link-home" href="<?php echo ROOT; ?>admin">Home</a>
			<a class="link" id="link-project" href="<?php echo ROOT; ?>admin/project">Projects</a>
			<a class="link" id="link-customer" href="<?php echo ROOT; ?>admin/customer">Customers</a>
			<a class="link" id="link-resource" href="<?php echo ROOT; ?>admin/resource">Resources</a>
		</div>
		<div id="hright">
			<a class="link" id="link-logout" href="">Log out</a>
		</div>
	</div>
	<div id="content">
		<?php  echo $this->layout()->content ?>
		<div class="clear"></div>
	</div>
	<div id="footer">
		&copy; Copyright 2013 - The ITs
	</div>
</div>


</body>
</html>