<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd"> 
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=ISO-8859-1" />
	<?php echo $this->headTitle(); ?>
	<?php echo $this->loadSkin($this->skin); ?>
	<?php echo $this->headScript(); ?>
	<?php echo $this->headLink(); ?>
	
<title><?php echo $this->escape($this->pageTitle); echo " - Binary Vibes BizSense"; ?></title>
        <?php echo $this->dojo();
             echo $this->dojo()->addStylesheetModule('dijit.themes.tundra');

       ?>
</head>
<body class="tundra">
 
 <div id="wrapper">
            <?php  echo $this->layout()->content ?>
 </div>


</body>
</html>